name: docker-image-centos7_8

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'centos7_8/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'centos7_8/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get current timestamp
      run: |
        TIMESTAMP=$(date "+%Y%m%d%H%M%S")
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
    - name: Build the Docker image
      run: |
        cd centos7_8
        docker build . --file Dockerfile --tag cnzhanglu/nuitka_build_os:centos7.8.2003
        docker tag cnzhanglu/nuitka_build_os:7.8.2003 cnzhanglu/nuitka_build_os:centos7.8.2003.${{ env.TIMESTAMP }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push cnzhanglu/nuitka_build_os:centos7.8.2003
        docker push cnzhanglu/nuitka_build_os:centos7.8.2003.${{ env.TIMESTAMP }}
