name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd centos7_8
        docker build . --file Dockerfile --tag cnzhanglu/nuitka_build_os:7.8.2003
        docker tag cnzhanglu/nuitka_build_os:7.8.2003 cnzhanglu/nuitka_build_os:7.8.2003.$(date +%s)

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push cnzhanglu/nuitka_build_os:7.8.2003
        docker push cnzhanglu/nuitka_build_os:7.8.2003.$(date +%s)
