name: docker-image-centos6_10

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'centos6_10/**'
      - '.github/workflows/docker-image-centos6_10.yml'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'centos6_10/**'
      - '.github/workflows/docker-image-centos6_10.yml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get current timestamp
      run: |
        TIMESTAMP=$(date "+%Y%m%d%H%M%S")
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
    - name: Build the Docker image
      run: |
        cd centos7_8
        docker build . --file Dockerfile --tag cnzhanglu/nuitka_build_os:centos6.10
        docker tag cnzhanglu/nuitka_build_os:centos6.10 cnzhanglu/nuitka_build_os:centos6.10.${{ env.TIMESTAMP }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push cnzhanglu/nuitka_build_os:centos6.10
        docker push cnzhanglu/nuitka_build_os:centos6.10.${{ env.TIMESTAMP }}
